//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
[System.Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[System.Xml.Serialization.XmlType(TypeName = "methodCall", Namespace = "", AnonymousType = false)]
[System.Xml.Serialization.XmlRoot(Namespace="", IsNullable=false)]
public class SearchSubtitlesRawRequest{
    
    private string methodNameField;
    
    private Param[] paramsField;
    
    /// <remarks/>
    public string methodName {
        get {
            return methodNameField;
        }
        set {
            methodNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem("param", IsNullable=false)]
    public Param[] @params {
        get {
            return paramsField;
        }
        set {
            paramsField = value;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [System.Serializable()]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(TypeName = "methodCall", Namespace = "", AnonymousType = false)]
    public class Param
    {

        private ParamValue valueField;

        /// <remarks/>
        public ParamValue value
        {
            get
            {
                return valueField;
            }
            set
            {
                valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [System.Serializable()]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(TypeName = "methodCall", Namespace = "", AnonymousType = false)]
    public class ParamValue
    {

        private ParamValueArray arrayField;

        private string stringField;

        /// <remarks/>
        public ParamValueArray array
        {
            get
            {
                return arrayField;
            }
            set
            {
                arrayField = value;
            }
        }

        /// <remarks/>
        public string @string
        {
            get
            {
                return stringField;
            }
            set
            {
                stringField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [System.Serializable()]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(TypeName = "methodCall", Namespace = "", AnonymousType = false)]
    public class ParamValueArray
    {

        private ParamValueArrayValue[] dataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem("value", IsNullable = false)]
        public ParamValueArrayValue[] data
        {
            get
            {
                return dataField;
            }
            set
            {
                dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [System.Serializable()]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(TypeName = "methodCall", Namespace = "", AnonymousType = false)]
    public class ParamValueArrayValue
    {

        private ParamValueArrayValueMember[] structField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItem("member", IsNullable = false)]
        public ParamValueArrayValueMember[] @struct
        {
            get
            {
                return structField;
            }
            set
            {
                structField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [System.Serializable()]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(TypeName = "methodCall", Namespace = "", AnonymousType = false)]
    public class ParamValueArrayValueMember
    {

        private string nameField;

        private ParamValueArrayValueMemberValue valueField;

        /// <remarks/>
        public string name
        {
            get
            {
                return nameField;
            }
            set
            {
                nameField = value;
            }
        }

        /// <remarks/>
        public ParamValueArrayValueMemberValue value
        {
            get
            {
                return valueField;
            }
            set
            {
                valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCode("xsd", "4.0.30319.33440")]
    [System.Serializable()]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategory("code")]
    [System.Xml.Serialization.XmlType(TypeName = "methodCall", Namespace = "", AnonymousType = false)]
    public class ParamValueArrayValueMemberValue
    {

        private byte doubleField;

        private bool doubleFieldSpecified;

        private string stringField;

        /// <remarks/>
        public byte @double
        {
            get
            {
                return doubleField;
            }
            set
            {
                doubleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool doubleSpecified
        {
            get
            {
                return doubleFieldSpecified;
            }
            set
            {
                doubleFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string @string
        {
            get
            {
                return stringField;
            }
            set
            {
                stringField = value;
            }
        }
    }
}